version: '1.0'

services:
  payroll:
    build: .
    ports:
      - "5001:3000"
    volumes:
      - ./:/app

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - api
  #   ports:
  #     - 3000:3000

